# Generated by Django 6.0.3 on 2026-03-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
