# Generated by Django 4.2.29 on 2026-03-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
