# Generated by Django 4.2.29 on 2026-03-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='map_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='map_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
